Information: 20101 - Executed DbCommand (63ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `t`.`Id`, `t`.`Categoria`, `t`.`DataVencimento`, `t`.`Descricao`, `t`.`DthrReg`, `t`.`Pago`, `t`.`Parcela`, `t`.`Titulo`, `t`.`UserId`, `t`.`Valor`
FROM `tb_financ` AS `t`
Information: 20101 - Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `t`.`Id`, `t`.`Categoria`, `t`.`DataVencimento`, `t`.`Descricao`, `t`.`DthrReg`, `t`.`Pago`, `t`.`Parcela`, `t`.`Titulo`, `t`.`UserId`, `t`.`Valor`
FROM `tb_financ` AS `t`
Information: 20101 - Executed DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT `t`.`Id`, `t`.`Categoria`, `t`.`DataVencimento`, `t`.`Descricao`, `t`.`DthrReg`, `t`.`Pago`, `t`.`Parcela`, `t`.`Titulo`, `t`.`UserId`, `t`.`Valor`
FROM `tb_financ` AS `t`
